### ISSUE TITLE
Issue when try Optimise route for United States

### ISSUE THREAD

**Issue by saormart** [PGWelch/com.opendoorlogistics#48]
First of all, great project !
So, I was following [This Tutorial](https://www.youtube.com/watch?v=0DJdubVWX_A&t=113s) and it works fine if you select the UK map, but if you select the US (United States) and try to Optimise the route with the "ROAD_NETWORK" option selected on settings, I'm getting the following error:

java.lang.RuntimeException: Invalid or empty Graphhopper directory: C:\Demo\Graphhopper
	at com.opendoorlogistics.core.distances.DistancesSingleton.initGraphhopperGraph(DistancesSingleton.java:201)
	at com.opendoorlogistics.core.distances.DistancesSingleton.calculateGraphhopper(DistancesSingleton.java:119)
	at com.opendoorlogistics.core.distances.DistancesSingleton.calculate(DistancesSingleton.java:598)
	at com.opendoorlogistics.core.scripts.execution.dependencyinjection.AbstractDependencyInjector.calculateDistances(AbstractDependencyInjector.java:91)
	at com.opendoorlogistics.core.scripts.execution.ScriptExecutor$1.calculateDistances(ScriptExecutor.java:838)
	at com.opendoorlogistics.components.jsprit.VRPBuilder$VehicleRoutingTransportCostsImpl.<init>(VRPBuilder.java:190)
	at com.opendoorlogistics.components.jsprit.VRPBuilder.buildProblem(VRPBuilder.java:732)
	at com.opendoorlogistics.components.jsprit.VRPBuilder.build(VRPBuilder.java:742)
	at com.opendoorlogistics.components.jsprit.VRPComponent.runOptimiser(VRPComponent.java:503)
	at com.opendoorlogistics.components.jsprit.VRPComponent.execute(VRPComponent.java:273)
	at com.opendoorlogistics.core.scripts.execution.ScriptExecutor.executeSingleInstruction(ScriptExecutor.java:910)
	at com.opendoorlogistics.core.scripts.execution.ScriptExecutor.executeBatchedInstruction(ScriptExecutor.java:724)
	at com.opendoorlogistics.core.scripts.execution.ScriptExecutor.executeAllInstructions(ScriptExecutor.java:355)
	at com.opendoorlogistics.core.scripts.execution.ScriptExecutor.execute(ScriptExecutor.java:249)
	at com.opendoorlogistics.studio.scripts.execution.ScriptExecutionTask.executeNonEDTAfterInitialisation(ScriptExecutionTask.java:150)
	at com.opendoorlogistics.studio.scripts.execution.DatastoreModifierTask.executeNonEDT(DatastoreModifierTask.java:89)
	at com.opendoorlogistics.studio.scripts.execution.ScriptsRunner$2.doInBackground(ScriptsRunner.java:368)
	at com.opendoorlogistics.studio.scripts.execution.ScriptsRunner$2.doInBackground(ScriptsRunner.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Component com.opendoorlogistics.components.jsprit threw an exception.
Could not complete operation "vehicle routing (jsprit).odlx".
Execution of the operation failed.

**Comment by saormart** [comment]
Sorry, that was my fault !
I was reading the documents details, and I find out that I need to download the .osm.pbf file from [this link](http://download.geofabrik.de/), and execute the local .bat file with the correct parameters to generate all the required outputs for the application work properly !

Thanks !
